parameters:
    meup_kali_client.http_client.class:   GuzzleHttp\Client
    meup_kali_client.provider.class:      Meup\Bundle\KaliClientBundle\Provider\KaliProvider
    meup_kali_client.authenticator.class: Meup\Bundle\KaliClientBundle\Provider\KaliAuthenticator
    meup_kali_client.sku.class:           Meup\Bundle\KaliClientBundle\Model\Sku
    meup_kali_client.sku_factory.class:   Meup\Bundle\KaliClientBundle\Factory\SkuFactory
    meup_kali_client.sku_manager.class:   Meup\Bundle\KaliClientBundle\Manager\SkuManager

services:
    meup_kali_client.http_client:
        class: %meup_kali_client.http_client.class%
        arguments:
            - { 'base_uri': %kali_server%, 'http_errors': false }

    meup_kali_client.provider:
        class: %meup_kali_client.provider.class%
        arguments:
            - @meup_kali_client.http_client
            - @meup_kali_client.authenticator
        calls:
            - ['setLogger', [@logger]]

    meup_kali_client.authenticator:
        class: %meup_kali_client.authenticator.class%
        arguments:
            - @meup_kali_client.http_client
            - %kali_public_key%
            - %kali_secret_key%
        calls:
            - ['setLogger', [@logger]]

    meup_kali_client.sku_factory:
        class: %meup_kali_client.sku_factory.class%
        arguments:
            - %meup_kali_client.sku.class%
            - %app_name%

    meup_kali_client.sku_manager:
        class: %meup_kali_client.sku_manager.class%
        arguments:
            - @meup_kali_client.provider
            - @meup_kali_client.sku_factory
            - %app_name%
